### ISSUE TITLE
README iFrame is broken

### ISSUE THREAD

**Issue by ajmeese7** [prateekiiest/COVID-19-Analysis#1]
![image](https://user-images.githubusercontent.com/17814535/77698681-06924380-6f7f-11ea-855f-f64c1330bc2f.png)

Pasting the link into my browser shows it isn't broken, so it must be a markdown issue. Just thought you might not be tracking.

Keep up the good work, cheers!

**Comment by prateekiiest** [comment]
Oh!
Didn't notice that. 
Thanks @ajmeese7 for pointing this. ❤️
